### ISSUE TITLE
Bump to .NET 9 Release

### ISSUE THREAD

**Issue by driver1998** [loongson-community/dotnet-unofficial-build#2]
.NET 9 is finally released, time to bump to the final release.

https://devblogs.microsoft.com/dotnet/announcing-dotnet-9/
VMR: https://github.com/dotnet/dotnet/releases/tag/v9.0.0

**Comment by xen0n** [comment]
Working on this.

**Comment by Everyyx** [comment]
> Working on this.

Will Skiasharp2.8.8.9  be avaliable ？or ,who can teanch me how to compile? I have a 3A6000 desktop computer on my end

**Comment by xen0n** [comment]
> > Working on this.
> 
> Will Skiasharp2.8.8.9 be avaliable ？or ,who can teanch me how to compile? I have a 3A6000 desktop computer on my end

This project is only concerned with providing a .NET SDK build suitable for devs to pick up and develop their own things with. Due to limited manpower (currently only me), we do not mean to provide builds of any popular nuget packages right now, let alone a specific version like you requested.

You can try porting the library with official SkiaSharp instructions, that is, become a SkiaSharp contributor. Or if the version is not the latest (hence impossible to retroactively add support), ask around in places like [LA UOSC](https://bbs.loongarch.org). Personally I don't know how to do this nor have the time to learn then teach you; apologizes for that.

**Comment by driver1998** [comment]
https://github.com/loongson-community/dotnet-unofficial-build/releases/tag/v9.0.0%2Bloong.20241120.build.20241121

**Comment by Everyyx** [comment]
Thanks for the reply！

________________________________
发件人: WÁNG Xuěruì ***@***.***>
发送时间: 2024年11月18日 19:17
收件人: loongson-community/dotnet-unofficial-build ***@***.***>
抄送: Monty Green ***@***.***>; Comment ***@***.***>
主题: Re: [loongson-community/dotnet-unofficial-build] Bump to .NET 9 Release (Issue #2)


Working on this.

Will Skiasharp2.8.8.9 be avaliable ？or ,who can teanch me how to compile? I have a 3A6000 desktop computer on my end

This project is only concerned with providing a .NET SDK build suitable for devs to pick up and develop their own things with. Due to limited manpower (currently only me), we do not mean to provide builds of any popular nuget packages right now, let alone a specific version like you requested.

You can try porting the library with official SkiaSharp instructions, that is, become a SkiaSharp contributor. Or if the version is not the latest (hence impossible to retroactively add support), ask around in places like LA UOSC<https://bbs.loongarch.org>. Personally I don't know how to do this nor have the time to learn then teach you; apologizes for that.

**Comment by Everyyx** [comment]
谢谢回复，已经看到最新发布了！您好，请教一下，新世界，使用Skiasharp 还需要参照 https://docs.loongnix.cn/dotnet/support/list/03.NET6%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html ，引用 loongarch版本的nupkg吗？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: driver1998 ***@***.***>
发送时间: 星期四, 十一月 21, 2024 8:53 上午
收件人: loongson-community/dotnet-unofficial-build ***@***.***>
抄送: Monty Green ***@***.***>; Comment ***@***.***>
主题: Re: [loongson-community/dotnet-unofficial-build] Bump to .NET 9 Release (Issue #2)


https://github.com/loongson-community/dotnet-unofficial-build/releases/tag/v9.0.0%2Bloong.20241120.build.20241121

―

**Comment by driver1998** [comment]
@Everyyx 新世界的Skiasharp和halfbuzz我记得loongarch QQ群（922566903）有人发过一个build，你可以过去问问

**Comment by Everyyx** [comment]
谢谢！

________________________________
发件人: driver1998 ***@***.***>
发送时间: 2024年11月21日 9:18
收件人: loongson-community/dotnet-unofficial-build ***@***.***>
抄送: Monty Green ***@***.***>; Mention ***@***.***>
主题: Re: [loongson-community/dotnet-unofficial-build] Bump to .NET 9 Release (Issue #2)


@Everyyx<https://github.com/Everyyx> 新世界的Skiasharp和harfbuzzsharp我记得loongarch QQ群（922566903）有人发过一个build，你可以过去问问

―

**Comment by xen0n** [comment]
> 新世界，使用Skiasharp 还需要参照 https://docs.loongnix.cn/dotnet/support/list/03.NET6%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html ，引用 loongarch版本的nupkg吗？

新世界禁止用 Loongnix 的各种源，除非他们声称自己是新世界 / ABI2.0 的。

因为这些源存在的意义就是防止工具去上游/社区源从而拉回适用新世界的包，你在新世界也配置用这些源的话，就会往本地拉回旧世界包了
